### ISSUE TITLE
training error no attribute 'outbound_nodes'

### ISSUE THREAD

**Issue by slajar** [Hguimaraes/gtzan.keras#11]
I ran the training but it gives me the error below. Actually, I have tensorflow 1.13.1. Does this cause the issue? I had to change the requirements.txt file to get this running. If this may be the problem, I'll consider downgrading. Thanks for any help.

Colocations handled automatically by placer.
Traceback (most recent call last):
  File "gtzan.py", line 131, in <module>
    main(args)
  File "gtzan.py", line 75, in main
    cnn = build_model(input_shape, num_genres)
  File "/Users/matthias/dev/GitHub/gtzan.keras/src/gtzan/model.py", line 16, in build_model
    input_tensor=input_tensor)
  File "/usr/local/lib/python3.7/site-packages/keras_applications/vgg16.py", line 116, in VGG16
    name='block1_conv1')(img_input)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 584, in __call__
    inputs, outputs, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1416, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1524, in _add_inbound_node
    arguments=arguments)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1742, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

**Comment by Hguimaraes** [comment]
Hi @slajar,

The previous version of tensorflow was causing some issues.
I just update a new version of the project in commit e3f5eba.
I updated the packages (including tensorflow), the architecture and a lot of conceptual details that was wrong, but the performance is similar. Please check out and contact me if something goes wrong.

Cheers,
