### ISSUE TITLE
Error, Model not defined

### ISSUE THREAD

**Issue by whoislewys** [Hguimaraes/gtzan.keras#8]
## After cloning and running, I get this error:
`
Traceback (most recent call last):
  File "gtzan.py", line 131, in <module>
    main(args)
  File "gtzan.py", line 75, in main
    cnn = build_model(input_shape, num_genres)
  File "C:\Users\lewys\PycharmProjects\genre-classification\gtzan.keras\src\gtzan\model.py", line 24, in build_model
    model = Model(inputs=vgg16.input, outputs=top(vgg16.output))
`

Should be a quick fix with a simple ` from keras import Model` in src\gtzan\model.py

Maybe you created this on a different version of Keras than I have installed? Could you please update the repo with a conda environment.yml file or similar to show which packages at which versions you have installed? Thanks

**Comment by whoislewys** [comment]
my bad, didnt notice notice requirements.txt

**Comment by HachimiLearning** [comment]
@whoislewys IN MY CASE, I HAVE THE SAME REQUIREMENTS AND STILL HAVE THE SAME ERROR 
58892288/58889256 [==============================] - 71s 1us/step
Traceback (most recent call last):
  File "gtzan.py", line 131, in <module>
    main(args)
  File "gtzan.py", line 75, in main
    cnn = build_model(input_shape, num_genres)
  File "C:\Users\AN94590\Desktop\UpScaleTech\gtzan.keras-master\src\gtzan\model.py", line 24, in build_model
    model = Model(inputs=vgg16.input, outputs=top(vgg16.output))
NameError: name 'Model' is not defined

Help please ?
